### Numpy Assignment

#### 1. What is a Python library? Why do we use Python libraries?

#### 2. What is the difference between Numpy array and List?

In [1]:
import numpy as np

#### 3. Find the shape, size and dimension of the following array?

##### [[1, 2, 3, 4]
##### [5, 6, 7, 8],
##### [9, 10, 11, 12]]

In [2]:
arr = np.asarray([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [3]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [4]:
arr.shape

(3, 4)

In [5]:
arr.size

12

In [6]:
arr.ndim

2

#### 4. Write python code to access the first row of the following array?

##### [[1, 2, 3, 4]

##### [5, 6, 7, 8],

##### [9, 10, 11, 12]]

In [7]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
arr[0]

array([1, 2, 3, 4])

#### 5. How do you access the element at the third row and fourth column from the given numpy array?

##### [[1, 2, 3, 4]

##### [5, 6, 7, 8],

##### [9, 10, 11, 12]]

In [9]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
arr[(2),(3)]

12

#### 6. Write code to extract all odd-indexed elements from the given numpy array?

##### [[1, 2, 3, 4]

##### [5, 6, 7, 8],

##### [9, 10, 11, 12]]

In [11]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
l = []

for i in range(0,3):
    for j in range(0,4):
        if i%2==0 and j%2==0:
            a = arr[(i),(j)]
            l.append(a)
print(f"List of all odd-indexed element is: {l}")

List of all odd-indexed element is: [1, 3, 9, 11]


#### 7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [13]:
random = np.random.rand(3,3)

In [14]:
random

array([[0.47234763, 0.64482472, 0.02492967],
       [0.29040708, 0.82094835, 0.99709519],
       [0.16306191, 0.65861368, 0.5001936 ]])

#### 8. Describe the difference between np.random.rand and np.random.randn?

In [15]:
np.random.rand(3,3)

array([[0.40426644, 0.36183827, 0.69599125],
       [0.09396581, 0.38680634, 0.16422535],
       [0.4650458 , 0.88006944, 0.6775557 ]])

In [16]:
np.random.randn(3,3)

array([[ 0.69961355, -0.36904919,  2.4276592 ],
       [-0.38779457,  1.92497183, -2.39848861],
       [ 0.89415685,  0.583148  ,  0.70530514]])

#### 9. Write code to increase the dimension of the following array?

##### [[1, 2, 3, 4]

##### [5, 6, 7, 8],

##### [9, 10, 11, 12]]

In [17]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
arr.ndim

2

###### Increasing Dimension using reshape function

In [19]:
arr_inc_d = arr.reshape(1,3,4)

In [20]:
arr_inc_d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [21]:
arr_inc_d.ndim

3

###### Increasing Dimension using expand_dims function

In [22]:
arr_expand_row = np.expand_dims(arr, axis = 0)

In [23]:
arr_expand_row

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [24]:
arr_expand_row.ndim

3

In [25]:
arr_expand_col = np.expand_dims(arr, axis = 1)

In [26]:
arr_expand_col

array([[[ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12]]])

In [27]:
arr_expand_col.ndim

3

#### 10. How to transpose the following array in NumPy?

##### [[1, 2, 3, 4]

##### [5, 6, 7, 8],

##### [9, 10, 11, 12]]

In [28]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
arr_transpose = arr.T

In [30]:
arr_transpose

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

#### 11. Consider the following matrix:

##### Matrix A: [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]

##### Matrix B: [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]


##### Perform the following operation using Python:
   1. Index wise multiplication
   2. Matrix multiplication
   3. Add both the matrics
   4. Subtract matrix B from A
   5. Divide Matrix B by A

In [31]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
B = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

In [32]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
B

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

###### 1. Index wise multiplication

In [34]:
A * B

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

###### 2. Matrix multiplication

In [35]:
A @ B

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

###### 3. Add both the matrics

In [36]:
A + B

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

###### 4. Subtract matrix B from A

In [37]:
B - A

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

###### 5. Divide Matrix B by A

In [38]:
B / A

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### 12.  Which function in Numpy can be used to swap the byte order of an array?

In [39]:
arrs = np.array([1, 2, 3], dtype=np.int16)

In [40]:
arrs

array([1, 2, 3], dtype=int16)

In [41]:
swapped_arr = arr.byteswap().newbyteorder()

In [42]:
swapped_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

#### 13.  What is the significance of the np.linalg.inv function?

In [43]:
arr1 = np.array([[1,2,1],[2,1,4],[5,2,1]])

In [44]:
arr1

array([[1, 2, 1],
       [2, 1, 4],
       [5, 2, 1]])

In [45]:
np.linalg.inv(arr1)

array([[-0.25      ,  0.        ,  0.25      ],
       [ 0.64285714, -0.14285714, -0.07142857],
       [-0.03571429,  0.28571429, -0.10714286]])

#### 14. What does the np.reshape function do, and how is it used?

In [46]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
arr.size

12

In [48]:
arr.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [49]:
arr.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

#### 15. What is broadcasting in Numpy?

The term broadcasting refers to how NumPy treats arrays with different dimensions during arithmetic operations which lead to certain constraints, the smaller array is broadcast across the larger array so that they have compatible shapes

In [50]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
arr + 5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

5 is broadcasted and added to every element

In [52]:
a = np.array([1,2,3,4])

In [53]:
a

array([1, 2, 3, 4])

In [54]:
arr + a

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12],
       [10, 12, 14, 16]])

a is broadcasted and added index-wise in rows of arr